# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: QAServers
  
variables:
  solution: 'AutomationTestingProgram.sln'
  project: 'AutomationTestingProgram/AutomationTestingProgram.csproj'
  frontendPath: 'AutomationTestingProgram/client'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.x'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '20.x'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(frontendPath)'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '$(frontendPath)'
    customCommand: 'run build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration) --output "$(build.artifactStagingDirectory)" /p:SkipInvalidConfigurations=true /p:DeployIisAppPath="Default Web Site"'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: WebApp