# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - 'Extension/*'
      - 'docs/*'
      - 'README.md'

name: $(Build.SourceBranchName).$(Rev:rr)

pool:
  name: QAServers
  demands: 884

variables:
  solution: 'AutomationTestingProgram.sln'
  project: 'AutomationTestingProgram/AutomationTestingProgram.csproj'
  projectTests: 'AutomationTestingProgram.UnitTests/AutomationTestingProgram.UnitTests.csproj'
  frontendPath: 'AutomationTestingProgram/client'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 8.0.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- task: NodeTool@0
  displayName: 'Use Node.js 22.x'
  inputs:
    versionSource: 'spec'
    versionSpec: '22.x'

- task: Npm@1
  displayName: 'npm ci --no-audit'
  inputs:
    command: 'ci'
    workingDir: '$(frontendPath)'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: 'custom'
    workingDir: '$(frontendPath)'
    customCommand: 'run build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    projects: '$(project)'
    arguments: '--configuration Release --output "$(build.artifactStagingDirectory)" /p:DeployIisAppPath="Default Web Site"'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet test'
#   inputs:
#     command: 'test'
#     projects: '$(projectTests)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Web App Artifact'
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: WebApp
